repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.257
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --preview
